name: Maelstrom Tests

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siddid-soni/dist-sys/maelstrom-rust:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
        
    - name: Build Rust project
      run: cargo build --release
      
    - name: Run Maelstrom echo test
      run: |
        /opt/maelstrom/maelstrom test -w echo --bin ./target/release/dist-sys --node-count 1 --time-limit 10
        
    - name: Run Maelstrom echo test (multiple nodes)
      run: |
        /opt/maelstrom/maelstrom test -w echo --bin ./target/release/dist-sys --node-count 3 --time-limit 10
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: maelstrom-test-results
        path: store/
        retention-days: 7
